SELECT USUARIOS.Id AS ID_USUARIO, Roles.Descripcion AS ROL,
USUARIOS.Usuario AS USERNAME, USUARIOS.Nombre AS NOMBRES, USUARIOS.Apellido AS APELLIDOS,
USUARIOS.FechaCreacion AS FECHA_CREACION,
CASE  
WHEN Activo = 1 THEN 'Activo'   
ELSE 'Baja'  
END  AS ESTADO
FROM USUARIOS
INNER JOIN ROLES ON
Usuarios.IdRol = Roles.Id
WHERE Usuarios.Id = 4
